### ISSUE TITLE
Compilation fails on Windows 

### ISSUE THREAD

**Issue by anatolat** [tibbe/network-bytestring#2]
Network-bytestring compilation fails on Windows platform.
Here's an error message:

> Building network-bytestring-0.1.3.1...
> Network\Socket\ByteString\Lazy.hsc:33:6:
>    parse error on input `getContents'

Here's patch that fixes this problem
http://pastebin.com/xfDmkW1D

**Comment by tibbe** [comment]
Fixed by 7ed54ccfa94021f95467dbe9792eb431b6f694de

**Comment by tibbe** [comment]
New version on Hackage.
