### ISSUE TITLE
Failed to install on Mac OS X 10.6

### ISSUE THREAD

**Issue by tianyicui** [tibbe/network-bytestring#3]
I know this package is merged into network. But I think submit an issue here might find me some help.

I was just trying to play with network programming in Haskell and `cabal install snap-server` failed with:
    snap-server-0.2.16.2 depends on network-bytestring-0.1.3.2 which failed to
    install.

My output of `cabal install network-bytestring --verbose=3` is at https://gist.github.com/704767

Thanks.

**Comment by tibbe** [comment]
It looks like `ghc-pkg dump` is failing. Try to run

```
/usr/local/bin/ghc-pkg dump --global -v2
```

and see if it exits abnormally.

**Comment by tibbe** [comment]
You can also try

```
strace -Ff -o log cabal install snap-server
```

and create a gist from the log file. I'm not sure if OS X 10.6 has strace. If not, try something like dtruss.

**Comment by tianyicui** [comment]
`/usr/local/bin/ghc-pkg dump --global -v2` exists normally and the output is https://gist.github.com/704827

**Comment by tibbe** [comment]
I spoke with Duncan Coutts (the Cabal maintainer) and he's not sure what's going on either. I'm worried that the exit code (11) is not the real exit code. See this:

http://stackoverflow.com/questions/1101957/are-there-any-standard-exit-status-codes-in-linux/1104641#1104641

**Comment by tianyicui** [comment]
BSDs do not have `strace`. In OSX 10.6 there are `dtrace` and `dtruss`. I'm not capable of using trace tools at all. The output of `sudo dtruss cabal install snap-server` is 749K long and cannot be put to gist. I'm not sure I'm doing it right. Please enlighten me how I can produce useful trace logs to help. Thanks.

**Comment by tianyicui** [comment]
I just tried compile it from source directly (HEAD version just checked out).

`cabal configure` mysteriously returned 11. And `runhaskell Setup.hs configure` said:

```
GHCi runtime linker: fatal error: I found a duplicate definition for symbol
_getProcessExitCode
whilst processing object file
/Users/tianyi/.cabal/lib/process-1.0.1.4/ghc-6.12.3/HSprocess-1.0.1.4.o
This could be caused by:
* Loading two different object files which export the same symbol
* Specifying the same object file twice on the GHCi command line
* An incorrect `package.conf' entry, causing some object to be
    loaded twice.
GHCi cannot safely continue in this situation.  Exiting now.  Sorry.
```

So I'm thinking this is likely to be something in my environment/configuration is broken, not bugs from Cabal or this package. I'll keep investigating. In the meantime you might want to stop wasting your precious time in this until I got something new to say. Thanks for your time!

**Comment by adept** [comment]
Btw, does "ghc-pkg check" report any errors?

**Comment by tianyicui** [comment]
Yes it reports https://gist.github.com/704905

I'll fix errors and try again. Thank you very much!

**Comment by tianyicui** [comment]
It's my configuration error. After removing `$HOME/{.ghc,.cabal}` everything works fine.
