### ISSUE TITLE
GHC 8.0.1 from haskell-platform

### ISSUE THREAD

**Issue by awgn** [tibbe/network-bytestring#4]
The library fails to compile with the following error:

[1 of 1] Compiling Network.Socket.ByteString ( dist/build/Network/Socket/ByteString.hs, dist/build/Network/Socket/ByteString.o )

Network/Socket/ByteString.cpphs:51:1: error:
    Failed to load interface for ‘GHC.IOBase’
    Perhaps you meant GHC.Base (from base-4.9.0.0)
    Use -v to see a list of the files searched for.

Thanks,
N.

**Comment by tibbe** [comment]
Hi,

Thanks for the report. network-bytestring is deprecated as its functionality has been merged back into the network package, so it's no longer maintained.
